# Generated by Django 5.0.2 on 2024-02-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.IntegerField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=40)),
                ('ContactName', models.CharField(max_length=25)),
                ('Address', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=20)),
                ('PostalCode', models.CharField(max_length=15)),
                ('Country', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.IntegerField(primary_key=True, serialize=False)),
                ('LastName', models.CharField(max_length=15)),
                ('FirstName', models.CharField(max_length=10)),
                ('BirthDate', models.DateField(auto_now_add=True)),
                ('Photo', models.CharField(max_length=45)),
                ('Notes', models.CharField(max_length=430)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.IntegerField(primary_key=True, serialize=False)),
                ('CustomerID', models.IntegerField()),
                ('EmployeeID', models.IntegerField()),
                ('OrderDate', models.DateField(auto_now_add=True)),
                ('ShipperDate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('OrderDetailID', models.IntegerField(primary_key=True, serialize=False)),
                ('OrderID', models.IntegerField()),
                ('ProductID', models.IntegerField()),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.IntegerField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=40)),
                ('SupplierID', models.IntegerField()),
                ('CategoryID', models.IntegerField()),
                ('Unit', models.CharField(max_length=25)),
                ('Price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('ShipperID', models.IntegerField(primary_key=True, serialize=False)),
                ('ShipperName', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('SupplierID', models.IntegerField(primary_key=True, serialize=False)),
                ('SupplierName', models.CharField(max_length=40)),
                ('ContactName', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=45)),
                ('City', models.CharField(max_length=15)),
                ('PostalCode', models.CharField(max_length=10)),
                ('Country', models.CharField(max_length=15)),
                ('Phone', models.CharField(max_length=15)),
            ],
        ),
    ]
